#!/bin/bash
API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT="data.json"

# Make the request
curl -s "$API_URL" -o "$OUTPUT"

# Check if the request was successful
if [ $? -ne 0 ]; then
	echo "Failed to fetch for pikachu" >> errors.txt
fi
