#!/bin/bash

pokemons=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")
API_URL="https://pokeapi.co/api/v2/pokemon/"

for name in "${pokemons[@]}"; do
	# convert name to lowercase for the URL
	name_lower=$(echo "$name"| tr '[:upper:]' '[:lower:]')

	#Fetch and save JSON
	curl -s "${API_URL}${name_lower}" -o "${name_lower}.json"

	if [ $? -ne 0 ]; then
		echo "Failed to fetch data for $name_lower" >> errors.txt
	else
		echo "Fetched data for $name_lower..."
		echo "Saved data to pokemon_data/bulbasaur.json ✅"
	fi

	# Delay to prevent rate limiting
	sleep 1
done
