#!/bin/bash

POKEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
API_URL="https://pokeapi.co/api/v2/pokemon/"
OUTPUT_DIR="pokemon_data"

# Ensure output folder exists
mkdir -p "$OUTPUT_DIR"

for name in "${POKEMON_LIST[@]}"; do
	#Fetch and save JSON
	curl -s "${API_URL}${name}" -o "$OUTPUT_DIR/${name}.json"

	if [ $? -ne 0 ]; then
		echo "Failed to fetch data for $name" >> errors.txt
	else
		echo "Fetched data for $name..."
		echo "Saved data to pokemon_data/bulbasaur.json ✅"
	fi

	# Delay to prevent rate limiting
	sleep 1
done
