#!/bin/bash

# Input JSON file
INPUT="data.json"

# Extract name, types, weight, height
name=$(jq -r '.name' "$INPUT")
type=$(jq -r '[.types[].type.name] | join(",")' "$INPUT")
formatted_weight=$(jq -r '.weight' "$INPUT" | awk '{printf "%.1f", $1 / 10}')
formatted_height=$(jq -r '.height' "$INPUT" | awk '{printf "%.1f", $1 / 10}')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

