#!/bin/bash

# Input JSON file
INPUT="data.json"

#Loop through each pokemon URL

jq -r '.results[].url' "$INPUT" | while read -r url; do
	# Fetch detailed pokemon data
	data=$(curl -s "$url")

	# Extract name, types, weight, height
	name=$(echo "$data" | jq -r '.name')
	types=$(echo "$data" | jq -r '[.types[].type.name] | join(",")')
	weight=$(echo "$data" | jq -r '.weight')
	height=$(echo "$data" | jq -r '.height')
echo "$name is of type $types, weighs $weight and is $height tall."
done
