#!/bin/bash

# Output CSV file
CSV_FILE="pokemon_report.csv"

# Write CSV header
echo "Name,Height (m),Weight (kg)" > "$CSV_FILE"

# Loop through all .json files
for file in  pokemon_data/*.json; do

	# Extract data
	name=$(jq -r '.name' $file)
	height=$(jq -r '.height' $file | awk '{printf "%.1f", $1 / 10}')  # decimeters to m
	weight=$(jq -r '.height' $file | awk '{printf "%.1f", $1 / 10}')  # hectogram to kg

	# Add row to csv
	echo "${name^},${height},${weight}" >> "$CSV_FILE"
done

# print the report
echo "CSV Report generated at: "$CSV_FILE""
echo
cat "$CSV_FILE"
echo

# Use awk to calculate averages (skip header row)
awk -F, 'NR > 1 {height += $2; weight += $3; count++} END {
	if(count > 0) {
		printf("Average Height: %.2f m\n", height / count)
		printf("Average Weight: %.2f kg\n", weight / count)
	}
}' "$CSV_FILE"
